openapi: 3.0.0
info:
  title: Naturally Good(Super Admin)
  description: API endpoints for Naturally Goods documented on Swagger
  contact:
    name: Deepak Singh
    email: deepak@techavtar.com
  version: 1.0.0
servers:
  - url: http://localhost:3001
    description: Local server

paths:
  /superadmin/create:
    post:
      summary: Create a new Super Admin
      security:
        - bearerAuth: []
      tags:
        - SuperAdmin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Name:
                  type: string
                  example: "John Doe"
                Email:
                  type: string
                  example: "john.doe@example.com"
                Password:
                  type: string
                  example: "Password123!"
                Role:
                  type: string
                  example: "superadmin"
      responses:
        201:
          description: SuperAdmin created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: SuperAdmin created successfully
        400:
          description: SuperAdmin already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: SuperAdmin already exists
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error
                  details:
                    type: string
                    example: Error details message


  